### ISSUE TITLE
'out' parameters should throw errors rather than silently convert to pointers

### ISSUE THREAD

**Issue by deckarep** [electronstudio/raylib-python-cffi#121]
Hello!

So far this is a great wrapper library but I'm having trouble with something that I thought would be trivial.

When it comes to user interaction with the checkbox: checking or unchecking no matter what I do I can't get the state of the checkbox to stay "checked" and the resulting boolean affected.

I feel like I'm doing something wrong but I've tried everything. One thing that I know works for sure is that if the boolean is toggled logically through code, the state of the checkbox gui element properly reflects that. But not the other way around.

```python
from pyray import *

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480


def main():
    init_window(SCREEN_WIDTH, SCREEN_HEIGHT, "Foo")
    set_exit_key(KeyboardKey.KEY_ESCAPE)
    set_target_fps(30)

    flag = True

    while not window_should_close():
        begin_drawing()
        clear_background(WHITE)

        gui_check_box(Rectangle(40, 40, 100, 100), "Just a checkbox", flag)

        end_drawing()


main()

```

Any help is appreciated!

**Comment by electronstudio** [comment]
Yes it's a 'bug', but you're found the workaround and I can't think of a better solution.

We could retain a handle to the created boolean pointer, but:
1. That would leak memory, if we just did it automatically.
2. There's no way of passing the handle back to the caller - the original Python boolean that the caller passed will not update when the C boolean does.

Arguably what we should do is refuse to accept Python booleans, throw an exception and tell the user about this workaround.

**Comment by deckarep** [comment]
Thank you for the prompt reply and explanation. I completely understand the issue and I think it makes more sense to do what you suggest in terms of the API user experience.

With an event loop game or gui app we certainly don't want to leak memory and I think throwing an error is better than accepting an argument which technically will not fully work correctly anyway especially since there is no real way of handling it properly.

Thanks for confirming my understanding and regardless this Python wrapper has been great to work with!

Perhaps I'll contribute a few examples to this repo at least to call out this behavior.

**Comment by electronstudio** [comment]
I think you're right.

Any examples you could contribute would be gratefully received; we are especially short of Raygui examples.

**Comment by electronstudio** [comment]
https://github.com/electronstudio/raylib-python-cffi/pull/122
