### ISSUE TITLE
How to use array in `draw_poly`?

### ISSUE THREAD

**Issue by xzripper** [electronstudio/raylib-python-cffi#124]
Drawing polygon in C:
```c
Vector2 points[] = {{200, 200}, {400, 200}, {450, 300}, {350, 400}, {250, 400}, {150, 300}};

DrawPoly(points, etc...);
```

Python:
```python
draw_poly([Vector2(200, 200), Vector2(400, 200), Vector2(450, 300), Vector2(350, 400), Vector2(250, 400), Vector2(150, 300)], etc...)
```

Exception:
`TypeError: float() not supported on cdata 'struct Vector2'`

How to add multiple points?

**Comment by electronstudio** [comment]
That's not how you draw a polygon in C.  The function is:

    void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color); 
   
It doesn't take an array.

You probably want `DrawLineStrip` instead.

**Comment by xzripper** [comment]
technically it is, thanks!
