### ISSUE TITLE
Add mypy support

### ISSUE THREAD

**Issue by Devourian** [electronstudio/raylib-python-cffi#136]
Hello, 
great project, I love it :rocket: 

I have one issue though:
have you thought about adding `mypy` support?
![image](https://github.com/user-attachments/assets/0ef7be98-bfee-4606-bc70-4bc5c6e82990)

Most Python projects use `mypy` nowadays and it would be great to have this in this project as well to provide some type safety to the projects using this library, maybe we could generate stubs using https://mypy.readthedocs.io/en/stable/stubgen.html#stubgen and then create `py.typed` marker file?

What do you think?

**Comment by electronstudio** [comment]
https://github.com/electronstudio/raylib-python-cffi/pull/135

**Comment by Devourian** [comment]
> #135

Ok, thanks, so the answer is still no?

Have you thought about this already?
> If we did enable type checking with the current fake type hints, how bad would it be? Do the examples pass type checking? If not, how much work would it be to make fake hints that are good enough for checking?
https://github.com/electronstudio/raylib-python-cffi/pull/135#issuecomment-2256456742

**Comment by electronstudio** [comment]
Should be working in 5.0.0.5
