### ISSUE TITLE
rlgl enums are missing

### ISSUE THREAD

**Issue by Yonokid** [electronstudio/raylib-python-cffi#139]
In my code I have only personally checked the gl blending factors from rlgh.h are missing, but I think there are more;
`rl_set_blend_factors_separate(RL_SRC_ALPHA, RL_ONE_MINUS_SRC_ALPHA, RL_ONE, RL_ONE_MINUS_SRC_ALPHA, RL_FUNC_ADD, RL_FUNC_ADD)` is not valid, but `rl_set_blend_factors_separate(0x302, 0x303, 1, 0x303, 0x8006, 0x8006)` is, so these enums work as intended but they are just missing their names; any clarification on this issue would be appreciated as I may have explained it poorly

**Comment by electronstudio** [comment]
```python
import pyray as pr
import raylib as rl
pr.rl_set_blend_factors_separate(rl.RL_SRC_ALPHA, rl.RL_ONE_MINUS_SRC_ALPHA, rl.RL_ONE, rl.RL_ONE_MINUS_SRC_ALPHA, rl.RL_FUNC_ADD, rl.RL_FUNC_ADD)

**Comment by electronstudio** [comment]
actually they are in the pyray namespace too, so not sure how youre missing them.  can just do
```python
import pyray as pr
pr.rl_set_blend_factors_separate(pr.RL_SRC_ALPHA, pr.RL_ONE_MINUS_SRC_ALPHA, pr.RL_ONE, pr.RL_ONE_MINUS_SRC_ALPHA, pr.RL_FUNC_ADD, pr.RL_FUNC_ADD)
```
