### ISSUE TITLE
Cannot Raylib running in Ubuntu Linux arm32 

### ISSUE THREAD

**Issue by Kaftorone** [electronstudio/raylib-python-cffi#141]
I used a latest version of python when build raylib from source I got this error

```bash
The error is `ModuleNotFoundError: No module named 'raylib._raylib_cffi'`
```

**Comment by electronstudio** [comment]
That is a runtime error that means the source build didn't complete, so we need the compile time error from the source build.

However I just fixed a couple of problems with the source build.  The new packages will be on pip tomorrow.  You can try it right now like this:

    python3 -m pip -vvv install https://github.com/electronstudio/raylib-python-cffi/archive/refs/tags/v5.0.0.4.tar.gz

**Comment by Kaftorone** [comment]
> That is a runtime error that means the source build didn't complete, so we need the compile time error from the source build.
> 
> However I just fixed a couple of problems with the source build.  The new packages will be on pip tomorrow.  You can try it right now like this:
> 
>     python3 -m pip -vvv install https://github.com/electronstudio/raylib-python-cffi/archive/refs/tags/v5.0.0.4.tar.gz
>

**Comment by electronstudio** [comment]
Static Raylib is required and some other things.  Instructions are here https://github.com/electronstudio/raylib-python-cffi/blob/master/BUILDING.rst
