### ISSUE TITLE
Typo in various Vector function names

### ISSUE THREAD

**Issue by Cramblioni** [electronstudio/raylib-python-cffi#148]
The naming convention for the various `Vector2*` and `Vector3*` seems to be `vector2_*` and `vector3_*`.

I've found the following functions that do not follow this convention.
- `vector_2distance`
- `vector_2distance_sqr`
- `vector_2divide`
- `vector_2dot_product`
- `vector_3distance`
- `vector_3distance_sqr`
- `vector_3divide`
- `vector_3dot_product`

I don't know if this is intentional, but it seems like a mistake.

I'm using the pypi copy (raylib 5.0.0.4 released 2024/10/2), though a quick code search shows that this issue is still present.

Sorry to nag.

**Comment by electronstudio** [comment]
Thanks for reporting, this should be fixed in https://github.com/electronstudio/raylib-python-cffi/pull/149/ .  Since it will break people's code I think we should wait for 5.5 release next month before merging.
