### ISSUE TITLE
CAMERA_ORBITAL issue

### ISSUE THREAD

**Issue by chriscamacho** [electronstudio/raylib-python-cffi#16]
I was looking round for a language I could teach my nephew coding, when I eventually found this module, it was great to see my shaders_basic_lighting example in python!

This should make it much easier to teach him!

However when I looked at the fog example, it didn't take long to find out the issue - reposition the camera and set it perspective and everything works! pesky orbital mode !

I've seen this issue with another earlier python wrapper, but its a bit of a puzzle, because once the camera mode is set it should be out of the hands of the wrapper - most puzzling!

BTW this is an excellent piece of work, ideal for teaching!

**Comment by electronstudio** [comment]
Your examples are great, thank you.  I just tried CAMERA_ORBITAL with the latest version 
676a29d  and it seems to work for me so closing this.
