### ISSUE TITLE
TextFormat - difficult to hold right...

### ISSUE THREAD

**Issue by chriscamacho** [electronstudio/raylib-python-cffi#20]
feels like I'm holding this wrong...

    #rl.DrawText(f"Frame: {int(frame)}".encode('UTF-8') , 10, 28, 20, MAROON)
    rl.DrawText(rl.TextFormat(b"Frame: %i",ffi.cast("int", frame)), 10, 28, 20, MAROON)

**Comment by electronstudio** [comment]
Not really sure what the issue is and probably solved yourself by now but reopen if not.
