### ISSUE TITLE
Fix setup tools to produce correctly named wheel files

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/raylib-python-cffi#25]
Currently we build wheel file with:

    python3 setup.py bdist_wheel

This produces `dist/raylib-3.5.0-py3-none-any.whl`.  It should produce something with e.g. `manylinux1_x86_64` rather than `any` architecture.

**Comment by akamensky** [comment]
Checking:

This is done by `ext_modules` section in `setup.py`: https://docs.python.org/3/distutils/setupscript.html#describing-extension-modules

Which is currently absent from it.
