### ISSUE TITLE
Build for ARM/raspberry pi

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/raylib-python-cffi#26]
Someone to do

    cd raylib-python-cffi/raylib/static
    ./build_linux_multi.sh
    
On RaspPi

**Comment by akamensky** [comment]
I've tried running on Ubuntu 20.04 64Bit (arch arm64). Where it fails to install Python 3.6. Didn't dig into why it fails yet.

**Comment by electronstudio** [comment]
I have updated and combined the build scripts.  You run them from the top level directory now.  Assuming they work on RPI could you please run `./raylib/static/build_multi_nox.sh` and then send me the wheels it builds in `dist` so I can upload them to pypi.  I am assuming `manylinux2014_armv7l` is the correct platform for the raspberry pi.  The alternate script `./raylib/static/build_multi.sh` will use whatever the platform defaults to but pypi doesnt seem to accept that.  Thanks.

**Comment by electronstudio** [comment]
@simonchatts (or anyone else with a RPI)

**Comment by electronstudio** [comment]
The build instructions now "work for me" on rpi3 but I'm not going to attempt to publish RPI bInaries with every release because I can't automate it with GitHub actions.
