### ISSUE TITLE
Update Raylib Version

### ISSUE THREAD

**Issue by Technisha** [electronstudio/raylib-python-cffi#28]
When will the libary be updated for Raylib 3.7? :p

**Comment by electronstudio** [comment]
Should be quite easy to do but currently I only have Linux setup to do builds. Need
* people to test new build system works
* People with windows or Mac who can submit builds

**Comment by electronstudio** [comment]
the source code in the git repo is now on Raylib 3.7.  Still need help making packages for pypi.

**Comment by Technisha** [comment]
Ah neat! Thanks!
