### ISSUE TITLE
Compile for web?

### ISSUE THREAD

**Issue by d1ddle** [electronstudio/raylib-python-cffi#45]
Is it possible to use raylib-python-cffi to develop a raylib game and compile it for html-5?
If so, how? Cross compile from python to C and use the normal raylib compiling method?
Many thanks

**Comment by electronstudio** [comment]
I don't know.  I don't know the current state of python-on-the-web but historically it wasn't good.  So first step would be working out how to get a Python program on the web.

I wasn't aware of any cross compiler from Python to C.

The old way was to transpile Python to Javascript, so if you did that you'd then need a Javascript graphics library, not a Python one.

Maybe ask on the Discord for suggestions.

**Comment by d1ddle** [comment]
Woah, Thanks for the swift reply, that was fast!
I'll definitely look at Cython. Would that *theoretically* mean that the Cython code could compile to raylib-web as if it were written in C from the beginning? I really want to avoid C.
Would that also mean I could use PyPy?
