### ISSUE TITLE
issue with running example from the fork reposetory

### ISSUE THREAD

**Issue by sDos280** [electronstudio/raylib-python-cffi#81]
I cloned that raylib-python-cffi repository into my pc but when I try to run the example I get that error.
I think the problem is that when I use the "from pyray import *" line it tries to import the pyray package that is provided with the repository and not with the pyray package that is installed on the **appdata\roaming\python\python310\site-packages** folder. does anyone know how to fix that?
![image](https://user-images.githubusercontent.com/107134807/190476968-baac9e6d-ed9f-4c48-b7fc-125ffb965d07.png)

**Comment by electronstudio** [comment]
It depends how you have setup your module search path, venv, if you are using an IDE, etc.  By default, running from the command line, Python will check for the module examples/shapes/pyray.  Assuming it doesn't find that, it will check site-packages/pyray and use that one.

**Comment by sDos280** [comment]
I am editing and running my files via pycharm, is there a way to explicitly tell it to use site-packages/pyray?

**Comment by electronstudio** [comment]
There probably is, but I don't know.  You could just delete raylib-python-cffi/pyray folder and then Pycharm will be unable to use that.

**Comment by sDos280** [comment]
ok, I tested that and I just needed to remove the raylib-python-cffi/pyray and the raylib-python-cffi/raylib. thanks :).

I have another question, why did I get the error when I tried to run it with the raylib-python-cffi/pyray and the raylib-python-cffi/raylib? like why would I get that error? isn't that folder should be the same as the one on the site-packages/pyray?

![image](https://user-images.githubusercontent.com/107134807/190617527-bf9131e4-3188-4ada-837f-b585b9375ddc.png)

**Comment by electronstudio** [comment]
It's because you haven't compiled the module.  To do that you would do `python raylib/build.py`.  But you're on Windows, so compiling is difficult, so I didn't suggest it as solution.

**Comment by sDos280** [comment]
is there another solution?

**Comment by sDos280** [comment]
ok, thanks for helping 🙃

**Comment by sDos280** [comment]
ok, thanks for helping 🙃
