### ISSUE TITLE
Unresolved reference `Color`, Pycharm issue

### ISSUE THREAD

**Issue by sDos280** [electronstudio/raylib-python-cffi#88]
while trying to use the Quickstart example in pycharm I Noticed that the IDE says that there is an error "unresolved reference 'WHITE'" and the error "unresolved reference 'VIOLET'". but when I tried to run the example it work perfectly. Is there a reason for this error?

example:
```python
from pyray import *
init_window(800, 450, "Hello")
while not window_should_close():
    begin_drawing()
    clear_background(WHITE)
    draw_text("Hello world", 190, 200, 20, VIOLET)
    end_drawing()
close_window()
```

error image:
![image](https://user-images.githubusercontent.com/107134807/191741599-7b837387-81e6-4853-8634-6a63663b0cce.png)

**Comment by sDos280** [comment]
ok, I think I understand why this is happening, that is just the way the library work. in any case thanks 🙃

**Comment by sDos280** [comment]
ok, I think I understand why this is happening, that is just the way the library work. in any case thanks 🙃

**Comment by electronstudio** [comment]
it's because we are using .pyi files to get PyCharm to do autocomplete, but the Colors were not listed in them.

**Comment by sDos280** [comment]
ok, so why did this run with no problem? how did the interpreter know what `WHITE`/`VIOLET` means?


also, I have this problem too (that isn't really an issue more like a question)
![image](https://user-images.githubusercontent.com/107134807/192051493-71caf6f8-e0b4-4377-9200-87a675d2db3a.png)
I know that the `KEY_RIGHT` is defied in the .pyi file but it is in the `KeyboardKey` class, so how does python know to pick/use that?

**Comment by electronstudio** [comment]
I think pyray.KEY_RIGHT is provided by CFFI. Then we later generated proper Python Enums from what CFFI provided, so we added pyray.KeyboardKey.KEY_RIGHT. But we allowed pyray. KEY_RIGHT to remain for backwards compatibility.

**Comment by sDos280** [comment]
That makes sense, thanks.
