### ISSUE TITLE
jpg image loading support

### ISSUE THREAD

**Issue by sDos280** [electronstudio/raylib-python-cffi#89]
the image in the image loading example is not loading, is that only on my PC?

![image](https://user-images.githubusercontent.com/107134807/191973172-fa37e1f8-1108-43fb-8cb4-136b3fd4bbb7.png)

**Comment by sDos280** [comment]
it seems like there is a problem with loading a `.jpn` file or with the `raylib_logo.jpg`.
with `image = LoadImage(b"resources/raylib_logo.png")` line it seem to work perfectly 
![image](https://user-images.githubusercontent.com/107134807/191974049-9e3d19e8-f128-4349-ad2d-057143857cc2.png)

**Comment by electronstudio** [comment]
The binaries I ship have jpeg support enabled.  If you compiled your own binaries then it will depend on how you compiled Raylib.  The default Raylib configuration does not enable jpeg.

**Comment by sDos280** [comment]
I compiled it with the pip (I imported pyray with the pip command...). it seems like the binaries that you shipped(if we are talking about the binary that I get with the pip command) haven't support for jpeg. at least for me...

**Comment by electronstudio** [comment]
Verified.  The binary builds do not include jpeg support even though we specify the option to cmake.  Raylib probably fucked up cmake again, or changed something without caring about backwards compatibility.  I'll investigate, but if it is a bug in Raylib cmake they usually say "cmake support is user contributed, we will not fix it".  Raylib is not a project known for its quality.

**Comment by sDos280** [comment]
ok, for now, I send a PR with the fix to this problem(by just using the raylib_logo.png) with some other things...
https://github.com/electronstudio/raylib-python-cffi/pull/86

**Comment by electronstudio** [comment]
I'd rather get jpg support working.

**Comment by sDos280** [comment]
ok, so do you want me to recommit/ remove https://github.com/electronstudio/raylib-python-cffi/pull/86/commits/8eb8a386fdf33ec908eeafcae83d2eed74bc7fd9?

**Comment by electronstudio** [comment]
no that's ok

**Comment by electronstudio** [comment]
I think the ugly way to do this is to hack raylib’s config.h before we build.

**Comment by electronstudio** [comment]
should be fixed when i release 5.0.0.1
