### ISSUE TITLE
Cannot find reference 'ffi' in 'pyray/__init__.pyi' And Unresolved reference '_raylib_cffi' in 'raylib/__init__.py'

### ISSUE THREAD

**Issue by sDos280** [electronstudio/raylib-python-cffi#91]
reference to #88 

![image](https://user-images.githubusercontent.com/107134807/192080567-57bcb084-39b9-4aa3-9a90-57c8742cb562.png)
![image](https://user-images.githubusercontent.com/107134807/192080713-8ff81460-8395-44bb-890e-8f5b624cf5c1.png)

**Comment by sDos280** [comment]
probably also only a "problem" with pycharm...

**Comment by electronstudio** [comment]
The first one I've fixed by changing the stub.  Not sure what can be done about the second one because that's from CFFI, but it's internal anyway so don't think users will see it.
