### ISSUE TITLE
pip pyray version is not updated to the main branch 

### ISSUE THREAD

**Issue by sDos280** [electronstudio/raylib-python-cffi#92]
I just checked again on the #88 problem with the pip bindings and it seems like there is still the same issue as in #88.
I confirmed that the pip version isn't updated by looking in the pyray/__init__.pyi (second to the last commit added the colors in the pyray/__init__.pyi)...

May you update the pip version?

**Comment by electronstudio** [comment]
I don’t make a new release every time the code changes. That would result in hundreds of releases.
